/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Color format accepted by the conversion functions.
 * Includes the two special request modes AUTO and OPTIMIZED in addition to all
 * concrete LVGL color formats.
 */
export declare const enum ColorFormat {
  /**
   * Automatically pick the smallest indexed tier (I1/I2/I4/I8) based on the
   * number of distinct colors in the source image.
   */
  AUTO = 'AUTO',
  /**
   * Like AUTO but also merges redundant transparent palette entries so the
   * palette may shrink to a smaller tier.
   */
  OPTIMIZED = 'OPTIMIZED',
  UNKNOWN = 'UNKNOWN',
  RAW = 'RAW',
  RAW_ALPHA = 'RAW_ALPHA',
  L8 = 'L8',
  I1 = 'I1',
  I2 = 'I2',
  I4 = 'I4',
  I8 = 'I8',
  A1 = 'A1',
  A2 = 'A2',
  A4 = 'A4',
  A8 = 'A8',
  AL88 = 'AL88',
  ARGB8888 = 'ARGB8888',
  XRGB8888 = 'XRGB8888',
  RGB565 = 'RGB565',
  ARGB8565 = 'ARGB8565',
  RGB565A8 = 'RGB565A8',
  RGB888 = 'RGB888',
  ARGB8888_PREMULTIPLIED = 'ARGB8888_PREMULTIPLIED',
  RGB565_SWAPPED = 'RGB565_SWAPPED'
}

/** Compression method for the binary payload. */
export declare const enum CompressMethod {
  NONE = 'NONE',
  RLE = 'RLE',
  LZ4 = 'LZ4'
}

/**
 * Options for converting an image to LVGL format.
 * All fields except `cf` are optional and fall back to sensible defaults.
 */
export interface ConvertOptions {
  /** Color format. Accepts any `ColorFormat` string value (e.g. `'RGB565'`). */
  cf: `${ColorFormat}`
  /** Background color packed as 0xRRGGBB. Defaults to `0`. */
  background?: number
  /** Stride alignment in bytes (any positive integer). Defaults to `1`. */
  align?: number
  /** Pre-multiply alpha into RGB channels. Defaults to `false`. */
  premultiply?: boolean
  /** Compression method. Accepts any `CompressMethod` string value. Defaults to `'NONE'`. */
  compress?: `${CompressMethod}`
  /** Enable dithering for RGB565 output. Defaults to `false`. */
  rgb565Dither?: boolean
  /** Enable Nema GFX compatible output. Defaults to `false`. */
  nemaGfx?: boolean
}

/** Options for decoding an LVGL image back to a standard format. */
export interface DecodeOptions {
  /** Set to `true` when the input is a C array produced by `imageToC`. Defaults to `false`. */
  isCArray?: boolean
}

export declare function imageToBin(input: Buffer, options: ConvertOptions): Buffer

export declare function imageToC(input: Buffer, inputName: string, outputName: string | undefined | null, options: ConvertOptions): string

export declare function lvglHeight(input: Buffer, options?: DecodeOptions | undefined | null): number

export declare function lvglToPng(input: Buffer, options?: DecodeOptions | undefined | null): Buffer

export declare function lvglToRgba(input: Buffer, options?: DecodeOptions | undefined | null): Buffer

export declare function lvglWidth(input: Buffer, options?: DecodeOptions | undefined | null): number
