/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function imageToBin(input: Buffer, cf: string, background: number, align: number, premultiply: boolean, compress: string): Buffer

export declare function imageToC(input: Buffer, inputName: string, outputName: string | undefined | null, cf: string, background: number, align: number, premultiply: boolean, compress: string): string

export declare function lvglHeight(input: Buffer, isCArray: boolean): number

export declare function lvglToPng(input: Buffer, isCArray: boolean): Buffer

export declare function lvglToRgba(input: Buffer, isCArray: boolean): Buffer

export declare function lvglWidth(input: Buffer, isCArray: boolean): number
