allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@img2lv/img2lv-darwin-arm64@0.2.1'
  - '@img2lv/img2lv-darwin-x64@0.2.1'
  - '@img2lv/img2lv-freebsd-x64@0.2.1'
  - '@img2lv/img2lv-linux-arm64-gnu@0.2.1'
  - '@img2lv/img2lv-linux-arm64-musl@0.2.1'
  - '@img2lv/img2lv-linux-x64-gnu@0.2.1'
  - '@img2lv/img2lv-linux-x64-musl@0.2.1'
  - '@img2lv/img2lv-wasm32-wasi@0.2.1'
  - '@img2lv/img2lv-win32-arm64-msvc@0.2.1'
  - '@img2lv/img2lv-win32-x64-msvc@0.2.1'
  - img2lv@0.2.1

supportedArchitectures:
  cpu:
    - current
    - wasm32
